"""
Standalone tasks logic (e.g. Thumbnail Only)
"""
import os
try:
    import yt_dlp as yt
    from yt_dlp.utils import sanitize_filename
except Exception:
    yt = None

from ...constants import RuntimeConfig
from ...core.models import DownloadResult
from ...utils.i18n_keys import Keys
from ...utils.console import console
from ...utils.network import check_internet
from ...ui.navigation import select_download_folder
from ...ui.provider import UIProvider, NullUI
from ...media.thumbnail import download_and_process_thumbnail, convert_thumbnail_format

def download_thumbnail_task(url, target_format='jpg', ui: UIProvider = NullUI()):
    """
    Standalone task for --thumbnail-only flag.
    Downloads cover art (Smart/YouTube) based on config without downloading media.
    """
    
    if RuntimeConfig.SIMPLE_MODE:
        target_dir = RuntimeConfig.THUMBNAIL_ROOT
    else:
        target_dir = select_download_folder(RuntimeConfig.THUMBNAIL_ROOT, "thumbnails")
        if not target_dir: return DownloadResult(success=False, reason='cancel')

    if not os.path.exists(target_dir):
        try:
            os.makedirs(target_dir, exist_ok=True)
        except OSError as e:
            console.err(Keys.media.cannot_create_thumb_dir(error=e))
            return DownloadResult(success=False)
    
    ui.clear()
    ui.header()

    if not check_internet():
        console.err(Keys.download.youtube.no_internet)
        return DownloadResult(success=False)

    try:
        with console.spin("Extracting information..."):
            with yt.YoutubeDL({'quiet': True, 'no_warnings': True}) as ydl:
                info = ydl.extract_info(url, download=False)
    except Exception as e:
        console.err(Keys.media.extraction_failed(error=e))
        return DownloadResult(success=False)

    if 'entries' in info:
        console.warn(Keys.media.playlist_detected(title=info.get('title')))
        entries = list(info['entries'])
        total = len(entries)
        console.proc(Keys.media.found_items_processing(count=total))
        
        success_count = 0
        first_path = None
        for i, entry in enumerate(entries, 1):
            console.proc(Keys.media.processing_entry(current=i, total=total, title=entry.get('title')))
            fpath = _process_single_thumbnail(entry, target_dir, target_format=target_format)
            if fpath:
                success_count += 1
                if not first_path:
                    first_path = fpath
        
        console.ok(Keys.media.processed_thumbnails(success=success_count, total=total))
        ui.wait_and_clear_prompt()
        target_dir_abs = os.path.abspath(target_dir)
        return DownloadResult(success=success_count > 0, file_path=target_dir_abs, file_count=success_count)
    else:
        fpath = _process_single_thumbnail(info, target_dir, target_format=target_format)
        ui.wait_and_clear_prompt()
        return DownloadResult(success=bool(fpath), file_path=fpath, file_count=1 if fpath else 0)

def _process_single_thumbnail(info, target_dir, target_format='jpg'):
    """Return path on success, None on failure."""
    title = info.get('title', 'Unknown')
    console.proc(Keys.media.processing_cover_for(title=title))

    uploader = info.get('uploader', '')
    description = info.get('description', '')
    
    is_art_track = (
        info.get('track') is not None or
        ' - Topic' in uploader or
        'Auto-generated by YouTube' in description or
        'Provided to YouTube by' in description
    )
    
    should_crop = is_art_track
    smart_search = RuntimeConfig.SMART_COVER_MODE and not is_art_track

    thumb_path, metadata = download_and_process_thumbnail(
        info, target_dir, should_crop=should_crop, smart_mode=smart_search
    )

    if thumb_path and os.path.exists(thumb_path):
        
        final_path = thumb_path
        if target_format != 'jpg':
            converted = convert_thumbnail_format(thumb_path, target_format)
            if converted:
                final_path = converted

        try:
            final_title = metadata.get('title') if metadata else title
            final_artist = metadata.get('artist') if metadata else info.get('uploader')
            
            ext = target_format
            
            if final_artist and final_title:
                new_name = f"{final_artist} - {final_title}.{ext}"
            else:
                new_name = f"{final_title}.{ext}"
            
            safe_name = sanitize_filename(new_name)
            new_path = os.path.join(target_dir, safe_name)
            
            if os.path.exists(new_path): os.remove(new_path)
            os.rename(final_path, new_path)
            
            console.ok(Keys.media.thumbnail_saved(name=safe_name))
            return os.path.abspath(new_path)
        except Exception:
            console.err(Keys.media.thumbnail_saved_as(name=os.path.basename(final_path)))
            return os.path.abspath(final_path)
    else:
        console.err(Keys.media.failed_to_download_thumbnail)
        return None