"""
Standalone tasks logic (e.g. Thumbnail Only)
"""
import os
try:
    import yt_dlp as yt
    from yt_dlp.utils import sanitize_filename
except Exception:
    yt = None

from ...constants import RuntimeConfig
from ...utils.i18n import get_text as _
from ...utils.styles import print_process, print_info, print_success, print_error, clear
from ...utils.spinner import Spinner
from ...utils.network import check_internet
from ...utils.display import wait_and_clear_prompt
from ...ui.components import header
from ...ui.navigation import select_download_folder
from ...media.thumbnail import download_and_process_thumbnail, convert_thumbnail_format

def download_thumbnail_task(url, target_format='jpg'):
    """
    Standalone task for --thumbnail-only flag.
    Downloads cover art (Smart/YouTube) based on config without downloading media.
    """
    
    if RuntimeConfig.SIMPLE_MODE:
        target_dir = RuntimeConfig.THUMBNAIL_ROOT
    else:
        target_dir = select_download_folder(RuntimeConfig.THUMBNAIL_ROOT, "thumbnails")
        if not target_dir: return {'success': False, 'reason': 'cancel'}

    if not os.path.exists(target_dir):
        try:
            os.makedirs(target_dir, exist_ok=True)
        except OSError as e:
            print_error(f"Cannot create thumbnail directory: {e}")
            return {'success': False}
    
    clear()
    header()

    if not check_internet():
        print_error(_('download.youtube.no_internet'))
        return {'success': False}

    spinner = Spinner("Extracting information...")
    spinner.start()

    try:
        with yt.YoutubeDL({'quiet': True, 'no_warnings': True}) as ydl:
            info = ydl.extract_info(url, download=False)
    except Exception as e:
        spinner.stop()
        print_error(f"Extraction failed: {e}")
        return {'success': False}

    spinner.stop()

    if 'entries' in info:
        print_info(f"Playlist detected: {info.get('title')}")
        entries = list(info['entries'])
        total = len(entries)
        print_process(f"Found {total} items. Processing thumbnails...")
        
        success_count = 0
        for i, entry in enumerate(entries, 1):
            print_process(f"[{i}/{total}] Processing: {entry.get('title')}")
            if _process_single_thumbnail(entry, target_dir, target_format=target_format):
                success_count += 1
        
        print_success(f"Processed {success_count}/{total} thumbnails.")
        wait_and_clear_prompt()
        return {'success': True}
    else:
        success = _process_single_thumbnail(info, target_dir, target_format=target_format)
        wait_and_clear_prompt()
        return {'success': success}

def _process_single_thumbnail(info, target_dir, target_format='jpg'):
    """Internal helper to process logic for a single info dict"""
    title = info.get('title', 'Unknown')
    print_process(f"Processing cover for: {title}")

    uploader = info.get('uploader', '')
    description = info.get('description', '')
    
    is_art_track = (
        info.get('track') is not None or
        ' - Topic' in uploader or
        'Auto-generated by YouTube' in description or
        'Provided to YouTube by' in description
    )
    
    should_crop = is_art_track
    smart_search = RuntimeConfig.SMART_COVER_MODE and not is_art_track

    thumb_path, metadata = download_and_process_thumbnail(
        info, target_dir, should_crop=should_crop, smart_mode=smart_search
    )

    if thumb_path and os.path.exists(thumb_path):
        
        final_path = thumb_path
        if target_format != 'jpg':
            converted = convert_thumbnail_format(thumb_path, target_format)
            if converted:
                final_path = converted

        try:
            final_title = metadata.get('title') if metadata else title
            final_artist = metadata.get('artist') if metadata else info.get('uploader')
            
            ext = target_format
            
            if final_artist and final_title:
                new_name = f"{final_artist} - {final_title}.{ext}"
            else:
                new_name = f"{final_title}.{ext}"
            
            safe_name = sanitize_filename(new_name)
            new_path = os.path.join(target_dir, safe_name)
            
            if os.path.exists(new_path): os.remove(new_path)
            os.rename(final_path, new_path)
            
            print_success(f"Saved: {safe_name}")
            return True
        except Exception:
            print_error(f"Saved as: {os.path.basename(final_path)}")
            return True
    else:
        print_error("Failed to download thumbnail.")
        return False