from __future__ import annotations

import os

from tetodl.core.models import DownloadResult
from tetodl.services.cover.image import fetch_image
from tetodl.services.cover.models import CoverData, CoverQuery
from tetodl.services.cover.processor import (
    convert_thumbnail_format,
    crop_thumbnail_to_square,
)
from tetodl.services.cover.providers import get_cover_providers
from tetodl.utils.console import console
from tetodl.utils.i18n_keys import Keys
from tetodl.utils.network import check_internet
from tetodl.utils.tracer import trace, traced

try:
    import yt_dlp as yt
    from yt_dlp.utils import sanitize_filename
except Exception:
    yt = None


class CoverService:

    def search(self, query: CoverQuery) -> CoverData | None:
        for provider in get_cover_providers():
            try:
                result = provider.search(query)
            except Exception:
                continue
            if result is not None and result.url:
                return result
        return None

    def fetch(self, url: str) -> bytes | None:
        return fetch_image(url)

    def process(self, filepath: str, crop: bool = False,
                target_format: str = "jpg") -> str | None:
        if crop:
            crop_thumbnail_to_square(filepath)
            return filepath
        result = convert_thumbnail_format(filepath, target_format)
        return result or filepath

    @trace
    def _process_entry(
        self,
        info: dict,
        target_dir: str,
        target_format: str = "jpg",
        smart_cover_mode: bool = True,
    ) -> str | None:
        title = info.get('title', 'Unknown')
        console.proc(Keys.media.processing_cover_for(title=title))

        uploader = info.get('uploader', '')
        description = info.get('description', '')

        is_art_track = (
            info.get('track') is not None
            or ' - Topic' in uploader
            or 'Auto-generated by YouTube' in description
            or 'Provided to YouTube by' in description
        )

        should_crop = is_art_track
        smart_search = smart_cover_mode and not is_art_track
        thumb_path = None
        metadata = None

        thumbnail_filename = f"{info.get('id', 'unknown')}.jpg"
        thumbnail_path = os.path.join(target_dir, thumbnail_filename)

        if smart_search:
            artist = info.get('artist') or info.get('uploader', '').replace(' - Topic', '')
            track_title = info.get('track') or info.get('title')
            if artist and track_title:
                query = CoverQuery(artist=artist, title=track_title)
                cover_data = self.search(query)
                if cover_data and cover_data.url:
                    img_data = self.fetch(cover_data.url)
                    if img_data is not None:
                        with open(thumbnail_path, 'wb') as f:
                            f.write(img_data)
                        source = cover_data.source
                        console.ok(Keys.download.youtube.fetch_success)
                        console.ok(Keys.media.cover_art_found_via(source=source))
                        thumb_path = thumbnail_path
                        metadata = cover_data

        if thumb_path is None:
            candidate_urls = []
            if info.get('thumbnail'):
                candidate_urls.append(info.get('thumbnail'))
            if info.get('thumbnails'):
                for t in reversed(info['thumbnails']):
                    if t.get('url') and t.get('url') not in candidate_urls:
                        candidate_urls.append(t['url'])

            for url in candidate_urls:
                img_data = self.fetch(url)
                if img_data is not None:
                    with open(thumbnail_path, 'wb') as f:
                        f.write(img_data)
                    thumb_path = thumbnail_path
                    break

        if thumb_path and os.path.exists(thumb_path):
            processed = self.process(thumb_path, crop=should_crop, target_format=target_format)
            thumb_path = processed or thumb_path

            final_path = thumb_path

            try:
                final_title = (getattr(metadata, 'title', None) or
                               metadata.get('title') if isinstance(metadata, dict) else None
                               or title)
                final_artist = (getattr(metadata, 'artist', None) or
                                metadata.get('artist') if isinstance(metadata, dict) else None
                                or info.get('uploader'))

                ext = target_format

                if final_artist and final_title:
                    new_name = f"{final_artist} - {final_title}.{ext}"
                else:
                    new_name = f"{final_title}.{ext}"

                safe_name = sanitize_filename(new_name)
                new_path = os.path.join(target_dir, safe_name)

                if os.path.exists(new_path):
                    os.remove(new_path)
                os.rename(final_path, new_path)

                console.ok(Keys.media.thumbnail_saved(name=safe_name))
                return os.path.abspath(new_path)
            except Exception:
                console.err(Keys.media.thumbnail_saved_as(
                    name=os.path.basename(final_path)))
                return os.path.abspath(final_path)

        console.err(Keys.media.failed_to_download_thumbnail)
        return None

    @trace
    def download(
        self,
        url: str,
        target_dir: str,
        target_format: str = "jpg",
        smart_cover_mode: bool = True,
    ) -> DownloadResult:
        if yt is None:
            return DownloadResult(success=False)

        if not os.path.exists(target_dir):
            try:
                os.makedirs(target_dir, exist_ok=True)
            except OSError as e:
                console.err(Keys.media.cannot_create_thumb_dir(error=str(e)))
                return DownloadResult(success=False)

        if not check_internet():
            console.err(Keys.download.youtube.no_internet)
            return DownloadResult(success=False)

        try:
            with console.spin("Extracting information..."):
                with yt.YoutubeDL({
                    'quiet': True, 'no_warnings': True,
                }) as ydl:
                    info = ydl.extract_info(url, download=False)
        except Exception as e:
            console.err(Keys.media.extraction_failed(error=str(e)))
            return DownloadResult(success=False)

        if 'entries' in info:
            playlist_title = info.get('title')
            console.warn(Keys.media.playlist_detected(title=playlist_title))
            entries = list(info['entries'])
            total = len(entries)
            console.proc(Keys.media.found_items_processing(count=total))
            success_count = 0
            first_path = None
            for i, entry in enumerate(entries, 1):
                console.proc(Keys.media.processing_entry(
                    current=i, total=total, title=entry.get('title')))
                fpath = self._process_entry(
                    entry, target_dir,
                    target_format=target_format,
                    smart_cover_mode=smart_cover_mode,
                )
                if fpath:
                    success_count += 1
                    if not first_path:
                        first_path = fpath
            console.ok(Keys.media.processed_thumbnails(
                success=success_count, total=total))
            target_dir_abs = os.path.abspath(target_dir)
            return DownloadResult(
                success=success_count > 0,
                file_path=target_dir_abs,
                file_count=success_count,
            )

        fpath = self._process_entry(
            info, target_dir,
            target_format=target_format,
            smart_cover_mode=smart_cover_mode,
        )
        return DownloadResult(
            success=bool(fpath),
            file_path=fpath,
            file_count=1 if fpath else 0,
        )


__all__ = ["CoverQuery", "CoverData", "CoverService"]
