"""
CoverStep — fetch, process, and embed cover art into audio files.
"""

import os
import subprocess
from typing import Optional

import requests

from ...constants import FFMPEG_CMD
from ...core.models import CoverConfig, CoverResult, DownloadedFile, LyricsMetadata, MediaInfo
from ...core.step import PipelineStep, PipelineError
from ...core.tagger import embed_metadata
from ...utils.i18n_keys import Keys
from ...utils.console import console
from ...core.metadata_fetcher import fetcher
from ...utils.files import clean_temp_files

FAKE_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/91.0.4472.124 Safari/537.36"
    ),
}


class CoverStep(PipelineStep):
    """Fetch, crop, and embed cover art into a downloaded audio file.

    Supports two strategies in order:
    1. **Smart cover** — query iTunes / Genius for high-quality artwork.
    2. **YouTube fallback** — download the best available thumbnail from
       the video metadata (``thumbnail`` or ``thumbnails`` list).

    When the source is an auto-generated YouTube Music track (``is_art_track``)
    the thumbnail is cropped to a 1:1 square.  Crop can also be forced via
    ``CoverConfig.force_crop``.
    """

    def __init__(
        self,
        config: Optional[CoverConfig] = None,
        is_youtube_music: bool = False,
        audio_format: str = "m4a",
    ) -> None:
        """Configure the cover step.

        Parameters
        ----------
        config : CoverConfig | None
            Cover art options (smart_mode, disabled, force_crop).
            When ``None`` defaults are used (smart_mode=True).
        is_youtube_music : bool
            True when the URL is a YouTube Music link.  Skips the
            auto-generated-track heuristics in ``_is_art_track``.
        audio_format : str
            Target audio extension.  Covers are skipped for ``opus``
            (no embedded cover support).
        """
        self._config = config or CoverConfig()
        self._is_youtube_music = is_youtube_music
        self._audio_format = audio_format

    def __call__(
        self,
        info: MediaInfo,
        downloaded: DownloadedFile,
        target_dir: str,
    ) -> Optional[CoverResult]:
        """Process and embed cover art.

        Parameters
        ----------
        info : MediaInfo
            Extracted media metadata (thumbnail, uploader, track, etc.).
        downloaded : DownloadedFile
            The successfully downloaded audio file.
        target_dir : str
            Directory used for temporary thumbnail files.

        Returns
        -------
        CoverResult | None
            Cover processing result, or ``None`` when cover art is
            disabled, format doesn't support covers, or processing
            fails.

        Raises
        ------
        PipelineError
            On unexpected errors during cover processing.
        """
        if self._config.disabled or self._audio_format == "opus":
            return None

        is_art = self._is_art_track(info)
        path = None
        fetched = None

        if self._config.smart_mode:
            path, fetched = self._smart_download(info, target_dir)

        if path is None:
            path = self._youtube_fallback(info, target_dir, is_art, self._config.force_crop)

        if path is None or not os.path.exists(path):
            console.err(Keys.download.youtube.cover_process_failed)
            return None

        console.proc(Keys.download.youtube.embedding_cover)
        meta = self._build_metadata(info, fetched, is_art)

        if embed_metadata(downloaded.path, path, self._audio_format, meta):
            console.ok(Keys.download.youtube.cover_success)
        else:
            console.err(Keys.download.youtube.cover_failed)

        clean_temp_files(target_dir, info.id)
        cropped = is_art or self._config.force_crop
        return CoverResult(
            thumbnail_path=path,
            metadata=self._to_lyrics_metadata(fetched),
            source=(
                "smart" if fetched else "youtube"
            ),
            cropped=cropped,
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _is_art_track(info: MediaInfo) -> bool:
        """Check whether the source is an auto-generated YouTube Music track.

        Heuristics: has explicit track / artist, uploader ends with
        " - Topic", or description contains auto-generation markers.
        """
        desc = (info.description or "").lower()
        is_topic = info.uploader.endswith(" - Topic")
        is_auto = "auto-generated by youtube" in desc or "provided to youtube by" in desc
        return info.track is not None or is_topic or is_auto

    @staticmethod
    def _smart_download(
        info: MediaInfo,
        target_dir: str,
    ) -> tuple[Optional[str], Optional[dict]]:
        """Try to fetch cover art from iTunes / Genius."""
        artist = info.artist or info.uploader.replace(" - Topic", "")
        title = info.track or info.title

        try:
            data = fetcher.fetch_metadata(artist, title)
        except Exception:
            return None, None

        if not data or not data.get("url"):
            return None, None

        image_url: str = data["url"]
        try:
            resp = requests.get(image_url, headers=FAKE_HEADERS, timeout=10)
            if resp.status_code != 200:
                return None, None
        except requests.RequestException:
            return None, None

        thumb_path = os.path.join(target_dir, f"{info.id}.jpg")
        with open(thumb_path, "wb") as f:
            f.write(resp.content)

        source_name = data.get("source", "iTunes")
        console.ok(Keys.download.youtube.fetch_success)
        console.ok(Keys.media.cover_art_found_via(source=source_name))
        return thumb_path, data

    @staticmethod
    def _youtube_fallback(
        info: MediaInfo,
        target_dir: str,
        is_art: bool,
        force_crop: bool = False,
    ) -> Optional[str]:
        """Download the best available YouTube thumbnail."""
        candidates: list[str] = []
        if info.thumbnail:
            candidates.append(info.thumbnail)
        for t in reversed(info.thumbnails):
            url = t.get("url")
            if url and url not in candidates:
                candidates.append(url)

        thumb_path = os.path.join(target_dir, f"{info.id}.jpg")
        downloaded = False

        for url in candidates:
            try:
                resp = requests.get(url, headers=FAKE_HEADERS, timeout=10)
                if resp.status_code != 200:
                    continue
                with open(thumb_path, "wb") as f:
                    f.write(resp.content)
                downloaded = True
                break
            except requests.RequestException:
                continue

        if not downloaded:
            return None

        perform_crop = is_art or force_crop
        if perform_crop:
            CoverStep._crop_to_square(thumb_path)
        else:
            converted = CoverStep._convert_format(thumb_path, "jpg")
            if converted:
                thumb_path = converted

        return thumb_path

    @staticmethod
    def _build_metadata(
        info: MediaInfo,
        fetched: Optional[dict],
        is_art_track: bool,
    ) -> dict:
        if fetched:
            return fetched
        if is_art_track or info.artist:
            return {
                "artist": info.artist or info.uploader.replace(" - Topic", ""),
                "album": info.album or info.title,
                "title": info.track or info.title,
            }
        return {}

    @staticmethod
    def _to_lyrics_metadata(fetched: Optional[dict]) -> Optional[LyricsMetadata]:
        """Convert a raw iTunes / Genius dict into a typed ``LyricsMetadata``."""
        if not fetched:
            return None
        year_raw: str | int | None = fetched.get("year") or fetched.get("date")
        if isinstance(year_raw, str):
            try:
                year_raw = int(year_raw[:4])
            except (ValueError, IndexError):
                year_raw = None
        return LyricsMetadata(
            artist=fetched.get("artist", ""),
            title=fetched.get("title", ""),
            album=fetched.get("album"),
            album_artist=fetched.get("album_artist"),
            genre=fetched.get("genre"),
            year=year_raw,
            composer=fetched.get("composer"),
            track_number=fetched.get("track_number"),
            disc_number=fetched.get("disc_number"),
            cover_url=fetched.get("url"),
        )

    @staticmethod
    def _crop_to_square(thumbnail_path: str) -> bool:
        """Crop a landscape thumbnail to 1:1 square via FFmpeg."""
        output = thumbnail_path + ".square.jpg"
        cmd = [
            FFMPEG_CMD,
            "-i", thumbnail_path,
            "-vf", "crop=min(iw\\,ih):min(iw\\,ih)",
            "-y",
            output,
        ]
        try:
            result = subprocess.run(cmd, capture_output=True, text=True)
            if result.returncode == 0 and os.path.exists(output):
                os.remove(thumbnail_path)
                os.rename(output, thumbnail_path)
                return True
            console.err(Keys.media.crop_failed(error=result.stderr))
            return False
        except Exception as exc:
            console.err(Keys.media.crop_error(error=str(exc)))
            return False

    @staticmethod
    def _convert_format(thumbnail_path: str, target_format: str) -> Optional[str]:
        """Convert image to target format via FFmpeg."""
        ext = target_format.lower().replace("jpeg", "jpg")
        root, _ = os.path.splitext(thumbnail_path)
        output = f"{root}.converted.{ext}"
        cmd = [FFMPEG_CMD, "-i", thumbnail_path, "-y", output]
        try:
            result = subprocess.run(cmd, capture_output=True, text=True)
            if result.returncode == 0 and os.path.exists(output):
                os.remove(thumbnail_path)
                return output
            return None
        except Exception:
            return None
