class SpotifyError(Exception):
    ...

class SpotifyAuthError(SpotifyError):
    ...

class SpotifyAPIError(SpotifyError):
    ...

class SpotifyRateLimitError(SpotifyAPIError):
    ...

class SpotifyParseError(SpotifyError):
    ...
